# -*- coding: utf-8 -*-
"""ONNXSchihtenmodifizeiren.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TRyhSocApu1N4tpQl6o-WR5BbXS4n9l
"""

!pip install onnx onnxruntime


from google.colab import drive
drive.mount('/content/drive')




import onnx
from onnx import helper

# Laden Sie Ihr ONNX-Modell
model_path = '/content/drive/My Drive/CNNMODEL/Mein_Trainiertes_Modellmi1Input-129.onnx'
onnx_model = onnx.load(model_path)

# Der Name der vorletzten Schicht, deren Ausgabe Sie extrahieren möchten
concat_layer_output_name = 'model/dense_6/MatMul'

# Stellen Sie sicher, dass diese Schicht als Ausgabe in der Graphendefinition vorhanden ist
# Falls nicht, fügen Sie sie als zusätzliche Ausgabe hinzu
if concat_layer_output_name not in [output.name for output in onnx_model.graph.output]:
    # Sie müssen die richtigen Shape-Informationen kennen oder diese aus dem Modell extrahieren
    concat_output_shape = [1, 1024] # Ersetzen Sie dies durch die tatsächliche Ausgabeform der Concat-Schicht
    concat_output_tensor = helper.make_tensor_value_info(concat_layer_output_name, onnx.TensorProto.FLOAT, concat_output_shape)
    onnx_model.graph.output.append(concat_output_tensor)

# Speichern Sie das modifizierte Modell
modified_model_path = '/content/drive/My Drive/CNNMODEL/Mein_Trainiertes_Modellmi1Input-129modifiziert.onnx'
onnx.save(onnx_model, modified_model_path)

import onnx
from onnx import helper

# Laden Sie Ihr ONNX-Modell
model_path = '/content/drive/My Drive/CNNMODEL/Mein_Trainiertes_Modellmi1Input-129.onnx'
onnx_model = onnx.load(model_path)

# Der Name der vorletzten Schicht, deren Ausgabe Sie extrahieren möchten
concat_layer_output_name = 'model/batch_normalization_10/batchnorm/mul_1:0'  # Ersetzen Sie dies durch den tatsächlichen Namen der MatMul-Schicht

# Stellen Sie sicher, dass diese Schicht als Ausgabe in der Graphendefinition vorhanden ist
# Falls nicht, fügen Sie sie als zusätzliche Ausgabe hinzu
if concat_layer_output_name not in [output.name for output in onnx_model.graph.output]:
    # Sie müssen die richtigen Shape-Informationen kennen oder diese aus dem Modell extrahieren
    concat_output_shape = [1, 128]  # Ersetzen Sie dies durch die tatsächliche Ausgabeform der Concat-Schicht
    concat_output_tensor = helper.make_tensor_value_info(concat_layer_output_name, onnx.TensorProto.FLOAT, concat_output_shape)
    onnx_model.graph.output.append(concat_output_tensor)

# Speichern Sie das modifizierte Modell
modified_model_path = '/content/drive/My Drive/CNNMODEL/Mein_Trainiertes_Modellmi1Input-129modifiziert4.onnx'
onnx.save(onnx_model, modified_model_path)

!pip install onnx onnxruntime

import onnx
from onnx import helper
from google.colab import drive
drive.mount('/content/drive')

# Laden Sie Ihr ONNX-Modell
model_path = '/content/drive/My Drive/CNNMODEL/input15.onnx'
onnx_model = onnx.load(model_path)

# Der Name der vorletzten Schicht, deren Ausgabe Sie extrahieren möchten
concat_layer_output_name = 'model_1/dense_2/BiasAdd:0'  # Der Name der MatMul-Schicht, wie in Ihrem Bild gezeigt

# Stellen Sie sicher, dass diese Schicht als Ausgabe in der Graphendefinition vorhanden ist
# Falls nicht, fügen Sie sie als zusätzliche Ausgabe hinzu
if concat_layer_output_name not in [output.name for output in onnx_model.graph.output]:
    # Sie müssen die richtigen Shape-Informationen kennen oder diese aus dem Modell extrahieren
    concat_output_shape = [1, 256]  # Ersetzen Sie dies durch die tatsächliche Ausgabeform der MatMul-Schicht
    concat_output_tensor = helper.make_tensor_value_info(concat_layer_output_name, onnx.TensorProto.FLOAT, concat_output_shape)
    onnx_model.graph.output.append(concat_output_tensor)

# Speichern Sie das modifizierte Modell
modified_model_path = '/content/drive/My Drive/CNNMODEL/input15modifizert4.onnx'
onnx.save(onnx_model, modified_model_path)